### ISSUE TITLE
An exception is thrown if there is no ad fill

### ISSUE THREAD

**Issue by easymarketingx** [ChartBoost/chartboost-mediation-unity-sdk#224]
Unity 2022.3.27f1c1
MAX Unity Plugins 8.0.1
Chartboost Adpater 9.8.1.0
Chartboost SDK 9.8.1

If there is no ad fill, execute load ad:

2024-12-16 17:40:47.246 29442-29784/? E/[ChartboostMonetization]: w1.a(): IFA: AdvertisingIDHolder(advertisingIDState=TRACKING_ENABLED, advertisingID=031586c7-5f4a-4f75-b718-fd30709a35e8)
2024-12-16 17:40:47.372 29442-29774/? E/[ChartboostMonetization]: j7.run(): parseServerResponse
    org.json.JSONException: End of input at character 0 of 
        at org.json.JSONTokener.syntaxError(JSONTokener.java:460)
        at org.json.JSONTokener.nextValue(JSONTokener.java:101)
        at org.json.JSONObject.<init>(JSONObject.java:168)
        at org.json.JSONObject.<init>(JSONObject.java:185)
        at com.chartboost.sdk.impl.z7.a(SourceFile:46)
        at com.chartboost.sdk.impl.j7.run(SourceFile:104)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by easymarketingx** [comment]
![chartboost_exception](https://github.com/user-attachments/assets/c21e4792-7b46-463f-9c2d-7bce434bbccd)

**Comment by SCastanedaMunoz** [comment]
@easymarketingx Thanks for letting us know, this issue should have been fixed this week server-side. Let us know if you keep encountering this problem.
